version: '2'
services:
  dnsmasq:
    build:
      dockerfile: Dockerfile
      context: .
    image: dnsmasq:build
    ports:
    - 53:53
    volumes:
    - ./dnsmasq.conf:/etc/dnsmasq.conf
    environment:
    - ADDRESS_1=/1.orange.com/192.168.1.1
    - ADDRESS_2=/2.orange.com/192.168.1.2
    - ADDRESS_3=/3.orange.com/192.168.1.3
